import fs from "node:fs";
import path from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { fileURLToPath } from "node:url";
import AdmZip from "adm-zip";
import type { UiPathTestAutomationArtifact } from "./types/uipath-solution";
import { fetchUiPathFolders, getUiPathConfig } from "./uipath-integration";
import { getAccessToken, getTmToken } from "./uipath-auth";
import { metadataService } from "./catalog/metadata-service";
import { getDefaultDotnetPath, getDefaultUiPathCliDllPath } from "./uipath-solution-cli";

const execFileAsync = promisify(execFile);

export type UiPathTestManagerLink = {
  testCaseName: string;
  tmTestCaseId: string;
  tmObjKey: string;
};

export type UiPathPublishLinkedTestsOptions = {
  artifact: UiPathTestAutomationArtifact;
  tmProjectId: string;
  testManagerBasePath: string;
  packageVersion?: string;
  tmProjectName?: string;
  folderPath?: string;
  links: UiPathTestManagerLink[];
};

export type UiPathPublishLinkedTestsResult = {
  projectDir: string;
  packagePath: string;
  packageVersion: string;
  deployStdout: string;
  deployStderr: string;
  linkedCount: number;
  totalLinksExpected: number;
};

type OrchestratorTestCaseDefinition = {
  Name?: string | null;
  UniqueId?: string | null;
  CreatedVersion?: string | null;
  LatestVersion?: string | null;
  LatestPrereleaseVersion?: string | null;
  CreationTime?: string | null;
};

function sanitizeFolderSegment(value: string, fallback: string): string {
  const cleaned = String(value || "").replace(/[^A-Za-z0-9._-]+/g, "_").replace(/^_+|_+$/g, "");
  return cleaned || fallback;
}

function readJsonFile(filePath: string): any {
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function writeJsonFile(filePath: string, value: unknown) {
  fs.writeFileSync(filePath, JSON.stringify(value, null, 2));
}

function buildTmConfig(
  artifact: UiPathTestAutomationArtifact,
  links: UiPathTestManagerLink[],
  testManagerBasePath: string,
): { issueKeyTestcaseValues: Record<string, string>; testManagerBasePath: string } {
  const linkByName = new Map(links.map((link) => [link.testCaseName.toLowerCase(), link]));
  const issueKeyTestcaseValues: Record<string, string> = {};

  for (const workflow of artifact.workflowMappings) {
    const match = linkByName.get(workflow.testCaseName.toLowerCase());
    if (!match?.tmObjKey) continue;
    issueKeyTestcaseValues[workflow.localTestCaseId] = match.tmObjKey;
  }

  return {
    issueKeyTestcaseValues,
    testManagerBasePath,
  };
}

function patchProjectJson(params: {
  projectJsonPath: string;
  artifact: UiPathTestAutomationArtifact;
  packageVersion: string;
  tmProjectName?: string;
}) {
  const { projectJsonPath, artifact, packageVersion, tmProjectName } = params;
  const projectJson = readJsonFile(projectJsonPath);
  const fileInfoCollection = Array.isArray(projectJson?.designOptions?.fileInfoCollection)
    ? projectJson.designOptions.fileInfoCollection
    : [];
  const mappingByFile = new Map(artifact.workflowMappings.map((mapping) => [mapping.fileName, mapping]));

  for (const entry of fileInfoCollection) {
    const mapping = mappingByFile.get(String(entry?.fileName || ""));
    if (!mapping) continue;
    entry.testCaseId = mapping.localTestCaseId;
    entry.testCaseType = "TestCase";
    entry.editingStatus = entry.editingStatus || "Publishable";
  }

  projectJson.projectVersion = packageVersion;
  projectJson.name = artifact.projectName;
  projectJson.main = artifact.workflowFiles[0] || projectJson.main;
  projectJson.description = projectJson.description || "Executable UiPath Test Automation project generated by CB2YY.";
  projectJson.designOptions = {
    ...(projectJson.designOptions || {}),
    outputType: "Tests",
    projectProfile: projectJson.designOptions?.projectProfile || "Developement",
    fileInfoCollection,
    saveToCloud: projectJson.designOptions?.saveToCloud ?? false,
  };
  projectJson.publishData = {
    ...(projectJson.publishData || {}),
    packageId: artifact.projectName,
    packageName: artifact.projectName,
    ...(tmProjectName ? { testManagerProjectName: tmProjectName } : {}),
  };

  writeJsonFile(projectJsonPath, projectJson);
}

function resolvePackedPackagePath(outputDir: string, packageVersion: string): string {
  const candidates = fs.readdirSync(outputDir)
    .filter((name) => name.toLowerCase().endsWith(".nupkg"))
    .map((name) => path.join(outputDir, name))
    .sort((a, b) => fs.statSync(b).mtimeMs - fs.statSync(a).mtimeMs);

  const exact = candidates.find((candidate) => candidate.toLowerCase().includes(packageVersion.toLowerCase()));
  if (exact) return exact;
  if (candidates[0]) return candidates[0];
  throw new Error(`No packed .nupkg was found in ${outputDir}`);
}

function createStableStageRoot(projectName: string): string {
  const moduleDir = path.dirname(fileURLToPath(import.meta.url));
  const workspaceStageRoot = path.resolve(moduleDir, "..", ".tmp", "uipath-tests-stage");
  fs.mkdirSync(workspaceStageRoot, { recursive: true });
  return fs.mkdtempSync(path.join(workspaceStageRoot, `${sanitizeFolderSegment(projectName, "UiPathTestsProject")}-`));
}

async function packUiPathTestsProject(projectDir: string, outputDir: string): Promise<string> {
  const dotnetPath = getDefaultDotnetPath();
  const cliDllPath = getDefaultUiPathCliDllPath();
  fs.mkdirSync(outputDir, { recursive: true });
  await execFileAsync(dotnetPath, [
    cliDllPath,
    "package",
    "pack",
    projectDir,
    "-o",
    outputDir,
  ], { windowsHide: true });
  return outputDir;
}

async function deployPackedUiPathTestsPackage(params: {
  packagePath: string;
  folderPath: string;
}): Promise<{ stdout: string; stderr: string }> {
  const config = await getUiPathConfig();
  if (!config) {
    throw new Error("UiPath config is not available for test package deployment.");
  }
  const dotnetPath = getDefaultDotnetPath();
  const cliDllPath = getDefaultUiPathCliDllPath();
  let stdout = "";
  let stderr = "";
  try {
    const result = await execFileAsync(dotnetPath, [
      cliDllPath,
      "package",
      "deploy",
      params.packagePath,
      "https://cloud.uipath.com/",
      config.tenantName,
      "-A",
      config.orgName,
      "-I",
      config.clientId,
      "-S",
      config.clientSecret,
      "--applicationScope",
      config.scopes || "OR.Default",
      "-o",
      params.folderPath,
      "-c",
      "false",
      "--traceLevel",
      "Information",
    ], { windowsHide: true });
    stdout = result.stdout;
    stderr = result.stderr;
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    const maybeStdout = typeof error === "object" && error && "stdout" in error ? String((error as any).stdout || "") : "";
    const maybeStderr = typeof error === "object" && error && "stderr" in error ? String((error as any).stderr || "") : "";
    if (!message.includes("Package already exists")) {
      throw error;
    }
    stdout = maybeStdout || message;
    stderr = maybeStderr;
  }

  return { stdout, stderr };
}

async function resolveFolderPath(preferredFolderPath?: string): Promise<string> {
  if (preferredFolderPath) return preferredFolderPath;
  const config = await getUiPathConfig();
  if (!config) {
    throw new Error("UiPath config is not available for folder resolution.");
  }
  if (config.folderName?.includes("/")) return config.folderName;
  if (config.folderId) {
    const folders = await fetchUiPathFolders();
    const match = folders.folders?.find((folder) => String(folder.id) === String(config.folderId));
    if (match?.fullyQualifiedName) {
      return match.fullyQualifiedName;
    }
  }
  if (config.folderName) return config.folderName;
  throw new Error("No UiPath folder is configured for test package deployment.");
}

export const __testUtils = {
  buildTmConfig,
  patchProjectJson,
};

async function fetchOrchestratorTestCaseDefinitions(packageIdentifier: string): Promise<OrchestratorTestCaseDefinition[]> {
  const config = await getUiPathConfig();
  if (!config) {
    throw new Error("UiPath config is not available for Orchestrator test case resolution.");
  }
  const orBase = metadataService.getServiceUrl("OR", config as any);
  const token = await getAccessToken({
    clientId: config.clientId,
    clientSecret: config.clientSecret,
    scopes: config.scopes || "OR.Default",
  });
  const response = await fetch(
    `${orBase}/odata/TestCaseDefinitions?$filter=PackageIdentifier eq '${packageIdentifier.replace(/'/g, "''")}'&$top=200`,
    {
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: "application/json",
      },
    },
  );
  const text = await response.text();
  if (!response.ok) {
    throw new Error(`Failed to fetch Orchestrator test case definitions: ${response.status} ${text.slice(0, 300)}`);
  }
  const payload = text ? JSON.parse(text) : {};
  return Array.isArray(payload?.value) ? payload.value : [];
}

function resolveAutomationIdsForArtifact(params: {
  artifact: UiPathTestAutomationArtifact;
  packageVersion: string;
  definitions: OrchestratorTestCaseDefinition[];
}): Map<string, string> {
  const byWorkflow = new Map<string, OrchestratorTestCaseDefinition[]>();
  for (const definition of params.definitions) {
    const key = String(definition.Name || "").toLowerCase();
    if (!key) continue;
    const list = byWorkflow.get(key) || [];
    list.push(definition);
    byWorkflow.set(key, list);
  }

  const resolved = new Map<string, string>();
  for (const workflow of params.artifact.workflowMappings) {
    const candidates = (byWorkflow.get(workflow.fileName.toLowerCase()) || []).filter((candidate) => {
      const createdVersion = String(candidate.CreatedVersion || "");
      const latestVersion = String(candidate.LatestVersion || "");
      const latestPrereleaseVersion = String(candidate.LatestPrereleaseVersion || "");
      const uniqueId = String(candidate.UniqueId || "");
      return createdVersion === params.packageVersion
        || latestVersion === params.packageVersion
        || latestPrereleaseVersion === params.packageVersion
        || uniqueId === workflow.localTestCaseId;
    });
    const fallbackCandidates = byWorkflow.get(workflow.fileName.toLowerCase()) || [];
    const selected = [...candidates, ...fallbackCandidates]
      .filter((candidate, index, all) => all.findIndex((item) => item.UniqueId === candidate.UniqueId) === index)
      .sort((left, right) => String(right.CreationTime || "").localeCompare(String(left.CreationTime || "")))[0];
    const automationId = String(selected?.UniqueId || "").trim();
    if (automationId) {
      resolved.set(workflow.testCaseName.toLowerCase(), automationId);
    }
  }

  return resolved;
}

async function updateTmAutomationLinks(params: {
  tmProjectId: string;
  tmProjectName?: string;
  artifact: UiPathTestAutomationArtifact;
  links: UiPathTestManagerLink[];
  packageVersion: string;
}) {
  const config = await getUiPathConfig();
  if (!config) {
    throw new Error("UiPath config is not available for Test Manager linking.");
  }
  const tmBase = metadataService.getServiceUrl("TM", config as any);
  const tmToken = await getTmToken();
  const headers = {
    Authorization: `Bearer ${tmToken}`,
    "Content-Type": "application/json",
    "X-UIPATH-TenantName": config.tenantName,
  };
  const workflowByName = new Map(
    params.artifact.workflowMappings.map((mapping) => [mapping.testCaseName.toLowerCase(), mapping]),
  );
  const automationIdByName = resolveAutomationIdsForArtifact({
    artifact: params.artifact,
    packageVersion: params.packageVersion,
    definitions: await fetchOrchestratorTestCaseDefinitions(params.artifact.projectName),
  });
  let linkedCount = 0;

  for (const link of params.links) {
    const workflow = workflowByName.get(link.testCaseName.toLowerCase());
    if (!workflow) continue;
    const automationTestCaseName = workflow.className;
    const automationId = automationIdByName.get(link.testCaseName.toLowerCase()) || null;
    const response = await fetch(`${tmBase}/api/v2/${params.tmProjectId}/testcases/${link.tmTestCaseId}/updateautomation`, {
      method: "POST",
      headers,
      body: JSON.stringify({
        ...(automationId ? { automationId } : {}),
        automationProjectName: params.tmProjectName || params.artifact.projectName,
        automationTestCaseName,
      }),
    });
    const text = await response.text();
    if (!response.ok) {
      throw new Error(`Failed to update Test Manager automation link for ${link.testCaseName}: ${response.status} ${text.slice(0, 200)}`);
    }
    linkedCount += 1;
  }

  return linkedCount;
}

export async function publishLinkedUiPathTestAutomationArtifact(
  options: UiPathPublishLinkedTestsOptions,
): Promise<UiPathPublishLinkedTestsResult> {
  const config = await getUiPathConfig();
  if (!config) {
    throw new Error("UiPath config is not available.");
  }

  const packageVersion = options.packageVersion || options.artifact.version;
  const tempRoot = createStableStageRoot(options.artifact.projectName);
  const projectRootName = sanitizeFolderSegment(options.artifact.projectName, "UiPathTestsProject");
  const projectDir = path.join(tempRoot, projectRootName);
  const packedDir = path.join(tempRoot, "packed");

  try {
    const zip = new AdmZip(options.artifact.buffer);
    zip.extractAllTo(tempRoot, true);

    const projectJsonPath = path.join(projectDir, "project.json");
    if (!fs.existsSync(projectJsonPath)) {
      throw new Error(`Generated test project is missing project.json at ${projectJsonPath}`);
    }

    patchProjectJson({
      projectJsonPath,
      artifact: options.artifact,
      packageVersion,
      tmProjectName: options.tmProjectName,
    });

    const tmhDir = path.join(projectDir, ".tmh");
    fs.mkdirSync(tmhDir, { recursive: true });
    writeJsonFile(path.join(tmhDir, "config.json"), buildTmConfig(
      options.artifact,
      options.links,
      options.testManagerBasePath,
    ));

    await packUiPathTestsProject(projectDir, packedDir);
    const packagePath = resolvePackedPackagePath(packedDir, packageVersion);
    const folderPath = await resolveFolderPath(options.folderPath);
    const deployResult = await deployPackedUiPathTestsPackage({
      packagePath,
      folderPath,
    });
    const linkedCount = await updateTmAutomationLinks({
      tmProjectId: options.tmProjectId,
      tmProjectName: options.tmProjectName,
      artifact: options.artifact,
      links: options.links,
      packageVersion,
    });

    return {
      projectDir,
      packagePath,
      packageVersion,
      deployStdout: deployResult.stdout,
      deployStderr: deployResult.stderr,
      linkedCount,
      totalLinksExpected: options.links.length,
    };
  } finally {
    fs.rmSync(tempRoot, { recursive: true, force: true });
  }
}
